import { useState, useEffect, useRef } from 'react';
import { Play, Pause, SkipForward, SkipBack, Volume2, Music } from 'lucide-react';
import { motion } from 'motion/react';

const TRACKS = [
  {
    id: 1,
    title: 'Neon Nights (Generated by AI)',
    author: 'AI Studio Alpha',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    duration: '6:12'
  },
  {
    id: 2,
    title: 'Cyber Pulse (Generated by AI)',
    author: 'AI Studio Beta',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    duration: '5:44'
  },
  {
    id: 3,
    title: 'Synthetic Dreams (Generated by AI)',
    author: 'AI Studio Gamma',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    duration: '5:02'
  }
];

export default function MusicPlayer() {
  const [currentTrack, setCurrentTrack] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [progress, setProgress] = useState(0);
  const audioRef = useRef<HTMLAudioElement>(null);

  useEffect(() => {
    if (audioRef.current) {
      if (isPlaying) {
        audioRef.current.play().catch((e) => console.log('Audio play failed:', e));
      } else {
        audioRef.current.pause();
      }
    }
  }, [isPlaying, currentTrack]);

  const handleTimeUpdate = () => {
    if (audioRef.current) {
      const current = audioRef.current.currentTime;
      const total = audioRef.current.duration;
      setProgress((current / total) * 100 || 0);
    }
  };

  const handleTrackEnd = () => {
    skipForward();
  };

  const togglePlay = () => setIsPlaying(!isPlaying);

  const skipForward = () => {
    setCurrentTrack((prev) => (prev + 1) % TRACKS.length);
    setIsPlaying(true);
  };

  const skipBackward = () => {
    setCurrentTrack((prev) => (prev - 1 + TRACKS.length) % TRACKS.length);
    setIsPlaying(true);
  };

  return (
    <div className="w-full max-w-sm bg-black/80 border border-fuchsia-500/30 rounded-xl p-6 shadow-[0_0_20px_rgba(217,70,239,0.15)] backdrop-blur-md relative overflow-hidden">
      {/* Decorative neon elements */}
      <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-cyan-400 to-transparent opacity-50" />
      <div className="absolute -inset-24 bg-fuchsia-500/10 blur-3xl rounded-full pointer-events-none" />

      <audio
        ref={audioRef}
        src={TRACKS[currentTrack].url}
        onTimeUpdate={handleTimeUpdate}
        onEnded={handleTrackEnd}
        preload="auto"
      />

      <div className="relative z-10">
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-cyan-500/20 border border-cyan-400 flex items-center justify-center shadow-[0_0_15px_rgba(34,211,238,0.4)]">
              <Music className="w-5 h-5 text-cyan-300" />
            </div>
            <div>
              <p className="text-xs text-cyan-400 font-mono tracking-wider mb-1 uppercase">Now Playing</p>
              <h3 className="text-sm font-medium text-white truncate w-48">
                {TRACKS[currentTrack].title}
              </h3>
              <p className="text-xs text-gray-400">{TRACKS[currentTrack].author}</p>
            </div>
          </div>
          {isPlaying && (
            <div className="flex gap-1 h-4 items-center">
              {[...Array(3)].map((_, i) => (
                <motion.div
                  key={i}
                  animate={{ height: ['4px', '16px', '4px'] }}
                  transition={{ repeat: Infinity, duration: 0.8, delay: i * 0.15 }}
                  className="w-1 bg-fuchsia-400 rounded-sm"
                />
              ))}
            </div>
          )}
        </div>

        {/* Progress bar */}
        <div className="w-full h-1 bg-gray-800 rounded-full mb-6 cursor-pointer relative overflow-hidden group">
          <motion.div
            className="absolute top-0 left-0 h-full bg-gradient-to-r from-cyan-500 to-fuchsia-500 shadow-[0_0_10px_rgba(217,70,239,0.5)]"
            style={{ width: `${progress}%` }}
            layout
          />
        </div>

        {/* Controls */}
        <div className="flex items-center justify-center gap-6">
          <button
            onClick={skipBackward}
            className="text-gray-400 hover:text-cyan-400 transition-colors duration-200"
          >
            <SkipBack className="w-6 h-6" />
          </button>
          
          <button
            onClick={togglePlay}
            className="w-14 h-14 flex items-center justify-center rounded-full bg-gradient-to-br from-cyan-500 to-fuchsia-600 text-white shadow-[0_0_20px_rgba(217,70,239,0.4)] hover:scale-105 hover:shadow-[0_0_30px_rgba(34,211,238,0.6)] transition-all duration-300 transform active:scale-95"
          >
            {isPlaying ? (
              <Pause className="w-6 h-6 fill-current" />
            ) : (
              <Play className="w-6 h-6 fill-current ml-1" />
            )}
          </button>

          <button
            onClick={skipForward}
            className="text-gray-400 hover:text-fuchsia-400 transition-colors duration-200"
          >
            <SkipForward className="w-6 h-6" />
          </button>
        </div>
      </div>
    </div>
  );
}
